# permissions for end users to view httproutegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: httproutegroup-viewer-role
rules:
- apiGroups:
  - specs.smi-spec.io
  resources:
  - httproutegroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - specs.smi-spec.io
  resources:
  - httproutegroups/status
  verbs:
  - get
