# permissions for end users to edit httproutegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: httproutegroup-editor-role
rules:
- apiGroups:
  - specs.smi-spec.io
  resources:
  - httproutegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - specs.smi-spec.io
  resources:
  - httproutegroups/status
  verbs:
  - get
