# permissions for end users to edit traffictargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traffictarget-editor-role
rules:
- apiGroups:
  - access.smi-spec.io
  resources:
  - traffictargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - access.smi-spec.io
  resources:
  - traffictargets/status
  verbs:
  - get
