# permissions for end users to view traffictargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traffictarget-viewer-role
rules:
- apiGroups:
  - access.smi-spec.io
  resources:
  - traffictargets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - access.smi-spec.io
  resources:
  - traffictargets/status
  verbs:
  - get
